#!/bin/sh

set -e

cd $(git rev-parse --show-toplevel)

# `cargo clippy` runs `cargo check`, which may produce warnings.
cargo clippy --all-targets --all-features -- --no-deps -D warnings
# (
#     cd proc-macro-crate
#     cargo clippy --all-targets --all-features -- -D warnings
# )
(
    cd charon/charon
    cargo clippy --all-targets --all-features -- -D warnings
)

cargo fmt --check
(
    cd proc-macro-crate
    cargo fmt --all --check
)
# (
#     cd charon/charon
#     cargo fmt --all --check
# )
