#!/bin/sh

set -e

cd $(git rev-parse --show-toplevel)

# `cargo clippy` runs `cargo check`, which may produce warnings.
cargo clippy --all-targets --all-features -- --no-deps -D warnings
# (
#     cd proc-macro-crate
#     cargo clippy --all-targets --all-features -- -D warnings
# )
# (
#     cd charon/charon
#     cargo clippy --all-targets --all-features -- -D warnings
# )

# `cargo fmt` does not support `--workspace`.
cargo fmt -p cargo-verify -p trust2-contract -p trust2-contract-macros -p utils --check
# (
#     cd proc-macro-crate
#     cargo fmt --check
# )
# (
#     cd charon/charon
#     cargo fmt --all --check
# )
(
    cd trust2-contract-verifier
    dune fmt --preview
)
(
    cd charon
    dune fmt --preview
)
